In [202]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [203]:
df = pd.read_csv("train.csv")

In [204]:
df.head(5)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [205]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [206]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [207]:
col = []
for x in df.columns:
    if len(df[x].unique()) > 20:
        continue
    col.append(x)
    print(f"{x}:")
    print(df[x].unique())

Survived:
[0 1]
Pclass:
[3 1 2]
Sex:
['male' 'female']
SibSp:
[1 0 3 4 2 5 8]
Parch:
[0 1 2 5 3 4 6]
Embarked:
['S' 'C' 'Q' nan]


In [208]:
for x in col:
    print(f"{x}:")
    for unit in df[x].unique():
        print(f"{unit}: {len(df[x][df[x] == unit])}")

Survived:
0: 549
1: 342
Pclass:
3: 491
1: 216
2: 184
Sex:
male: 577
female: 314
SibSp:
1: 209
0: 608
3: 16
4: 18
2: 28
5: 5
8: 7
Parch:
0: 678
1: 118
2: 80
5: 5
3: 5
4: 4
6: 1
Embarked:
S: 644
C: 168
Q: 77
nan: 0


In [209]:
for x in col:
    print(f"{x}:")
    for unit in df[x].unique():
        if unit is np.nan:
            continue
        print(f"{unit}: {len(df[x][df[x] == unit])} survive: {len(df[df[x] == unit][df['Survived'] == 1])}, percent: {len(df[df[x] == unit][df['Survived'] == 1])/len(df[df[x] == unit])}")
        

Survived:
0: 549 survive: 0, percent: 0.0
1: 342 survive: 342, percent: 1.0
Pclass:
3: 491 survive: 119, percent: 0.24236252545824846
1: 216 survive: 136, percent: 0.6296296296296297
2: 184 survive: 87, percent: 0.47282608695652173
Sex:
male: 577 survive: 109, percent: 0.18890814558058924
female: 314 survive: 233, percent: 0.7420382165605095
SibSp:
1: 209 survive: 112, percent: 0.5358851674641149
0: 608 survive: 210, percent: 0.34539473684210525
3: 16 survive: 4, percent: 0.25
4: 18 survive: 3, percent: 0.16666666666666666
2: 28 survive: 13, percent: 0.4642857142857143
5: 5 survive: 0, percent: 0.0
8: 7 survive: 0, percent: 0.0
Parch:
0: 678 survive: 233, percent: 0.34365781710914456
1: 118 survive: 65, percent: 0.5508474576271186
2: 80 survive: 40, percent: 0.5
5: 5 survive: 1, percent: 0.2
3: 5 survive: 3, percent: 0.6
4: 4 survive: 0, percent: 0.0
6: 1 survive: 0, percent: 0.0
Embarked:
S: 644 survive: 217, percent: 0.33695652173913043
C: 168 survive: 93, percent: 0.5535714285714286

C:\Users\adc05\AppData\Local\Temp\ipykernel_4648\1363470866.py:6: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  print(f"{unit}: {len(df[x][df[x] == unit])} survive: {len(df[df[x] == unit][df['Survived'] == 1])}, percent: {len(df[df[x] == unit][df['Survived'] == 1])/len(df[df[x] == unit])}")


In [210]:
df = df[col][df.isnull() == False]
Y = df["Survived"]
del col[col.index("Survived")]
X = df[col]
print(X)

     Pclass     Sex  SibSp  Parch Embarked
0         3    male      1      0        S
1         1  female      1      0        C
2         3  female      0      0        S
3         1  female      1      0        S
4         3    male      0      0        S
..      ...     ...    ...    ...      ...
886       2    male      0      0        S
887       1  female      0      0        S
888       3  female      1      2        S
889       1    male      0      0        C
890       3    male      0      0        Q

[891 rows x 5 columns]


In [211]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder

In [212]:
le = LabelEncoder()
X["Sex"] = le.fit_transform(X["Sex"])
X["Embarked"] = le.fit_transform(X["Embarked"])

C:\Users\adc05\AppData\Local\Temp\ipykernel_4648\3361421819.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X["Sex"] = le.fit_transform(X["Sex"])
C:\Users\adc05\AppData\Local\Temp\ipykernel_4648\3361421819.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X["Embarked"] = le.fit_transform(X["Embarked"])


In [213]:
print(X)

     Pclass  Sex  SibSp  Parch  Embarked
0         3    1      1      0         2
1         1    0      1      0         0
2         3    0      0      0         2
3         1    0      1      0         2
4         3    1      0      0         2
..      ...  ...    ...    ...       ...
886       2    1      0      0         2
887       1    0      0      0         2
888       3    0      1      2         2
889       1    1      0      0         0
890       3    1      0      0         1

[891 rows x 5 columns]


In [214]:
X = np.array(X)
Y = np.array(Y)
X_train, X_val, Y_train, Y_val = train_test_split(X,Y,random_state= 20)

In [215]:
print(X_train.shape,Y_train.shape,X_val.shape,Y_val.shape)

(668, 5) (668,) (223, 5) (223,)


In [216]:
model = RandomForestClassifier(n_estimators=500, max_depth=5, random_state=1, class_weight={0: 0.2, 1: 0.5, 2: 0.1, 3: 0.1, 4: 0.1})
model.fit(X_train, Y_train)

RandomForestClassifier(class_weight={0: 0.2, 1: 0.5, 2: 0.1, 3: 0.1, 4: 0.1},
                       max_depth=5, n_estimators=500, random_state=1)

In [217]:
y_pre =  model.predict(X_val)

In [218]:
matrix = confusion_matrix(Y_val,y_pre)

In [219]:
print(matrix)

[[111  31]
 [ 14  67]]


In [220]:
print((matrix[0][0] + matrix[1][1])/(sum(matrix[0]) + sum(matrix[1])))

0.7982062780269058


In [221]:
df_test = pd.read_csv("test.csv")

In [222]:
df_test

PassengerId  Pclass                                          Name  \
0            892       3                              Kelly, Mr. James   
1            893       3              Wilkes, Mrs. James (Ellen Needs)   
2            894       2                     Myles, Mr. Thomas Francis   
3            895       3                              Wirz, Mr. Albert   
4            896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)   
..           ...     ...                                           ...   
413         1305       3                            Spector, Mr. Woolf   
414         1306       1                  Oliva y Ocana, Dona. Fermina   
415         1307       3                  Saether, Mr. Simon Sivertsen   
416         1308       3                           Ware, Mr. Frederick   
417         1309       3                      Peter, Master. Michael J   

        Sex   Age  SibSp  Parch              Ticket      Fare Cabin Embarked  
0      male  34.5      0      0              330911    7.8292   NaN        Q  
1    female  47.0      1      0              363272    7.0000   NaN        S  
2      male  62.0      0      0              240276    9.6875   NaN        Q  
3      male  27.0      0      0              315154    8.6625   NaN        S  
4    female  22.0      1      1             3101298   12.2875   NaN        S  
..      ...   ...    ...    ...                 ...       ...   ...      ...  
413    male   NaN      0      0           A.5. 3236    8.0500   NaN        S  
414  female  39.0      0      0            PC 17758  108.9000  C105        C  
415    male  38.5      0      0  SOTON/O.Q. 3101262    7.2500   NaN        S  
416    male   NaN      0      0              359309    8.0500   NaN        S  
417    male   NaN      1      1                2668   22.3583   NaN        C  

[418 rows x 11 columns]

In [223]:
df_test = df_test[col][df_test.isnull() == False]
X_test = df_test[col]
X_test["Sex"] = le.fit_transform(X_test["Sex"])
X_test["Embarked"] = le.fit_transform(X_test["Embarked"])
print(X_test)

     Pclass  Sex  SibSp  Parch  Embarked
0         3    1      0      0         1
1         3    0      1      0         2
2         2    1      0      0         1
3         3    1      0      0         2
4         3    0      1      1         2
..      ...  ...    ...    ...       ...
413       3    1      0      0         2
414       1    0      0      0         0
415       3    1      0      0         2
416       3    1      0      0         2
417       3    1      1      1         0

[418 rows x 5 columns]


In [224]:
Y_pre = model.predict(X_test)

C:\Users\adc05\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\base.py:432: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(


In [225]:
df_test = pd.read_csv("test.csv")

In [226]:
re = df_test["PassengerId"]

In [227]:
df = pd.DataFrame({"PassengerId" : re, "Survived" : Y_pre})

In [228]:
df

PassengerId  Survived
0            892         0
1            893         1
2            894         0
3            895         0
4            896         1
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         1

[418 rows x 2 columns]

In [229]:
df.to_csv("submission.csv",index=False)